# Jellyfin Reverse Proxy Configuration
# Based on official Jellyfin documentation

<Location /jellyfin/socket>
    ProxyPreserveHost On
    ProxyPass ws://jellyfin:8096/jellyfin/socket
    ProxyPassReverse ws://jellyfin:8096/jellyfin/socket
</Location>

<Location /jellyfin>
    ProxyPass http://jellyfin:8096/jellyfin
    ProxyPassReverse http://jellyfin:8096/jellyfin
    ProxyPreserveHost On
    RequestHeader set X-Real-IP %{REMOTE_ADDR}s
    RequestHeader set X-Forwarded-For "%{REMOTE_ADDR}s"
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Host "%{HTTP_HOST}s"
</Location>
