# Tautulli Reverse Proxy Configuration
<Location /tautulli>
    ProxyPreserveHost On
    ProxyPass http://tautulli:8181/tautulli
    ProxyPassReverse http://tautulli:8181/tautulli
</Location>

<Location /tautulli/api>
    ProxyPreserveHost On
    ProxyPass http://tautulli:8181/tautulli/api
    ProxyPassReverse http://tautulli:8181/tautulli/api
</Location>

<Location /tautulli/newsletter>
    ProxyPreserveHost On
    ProxyPass http://tautulli:8181/tautulli/newsletter
    ProxyPassReverse http://tautulli:8181/tautulli/newsletter
</Location>

<Location /tautulli/image>
    ProxyPreserveHost On
    ProxyPass http://tautulli:8181/tautulli/image
    ProxyPassReverse http://tautulli:8181/tautulli/image
</Location>
